# ============================================================================
# NCA Assistant — Complete Analysis Record Export
# ============================================================================
# Generates a self-contained zip with results, settings, reproducibility
# script, data integrity hash, and summary document.

#' Generate the standalone reproducibility R script for NCA
#' @param settings List of NCA settings
#' @param col_map Column mapping
#' @param file_name Original data file name
#' @param blq_rule BLQ rule used
#' @param lloq LLOQ value
#' @param lz_overrides Named list of lambda_z overrides (subject -> list)
#' @return Character string containing the complete R script
generate_nca_script <- function(settings, col_map, file_name, blq_rule, lloq,
                                 lz_overrides = NULL) {
  
  adm_map <- c(extravascular = "Extravascular", iv_bolus = "Bolus",
                iv_infusion = "Infusion")
  adm <- adm_map[settings$admin_route]
  down <- if (settings$trap_method == "log") "Log" else "Linear"
  
  dose_code <- if (length(settings$dose) > 1) {
    paste0("# Per-subject doses (from Dose column)\n",
           "dose_df <- data %>%\n",
           "  dplyr::group_by(data[[\"", col_map$subject, "\"]]) %>%\n",
           "  dplyr::summarize(dose = max(data[[\"", col_map$dose, "\"]], na.rm = TRUE),\n",
           "                   .groups = \"drop\")\n",
           "dose_vec <- dose_df$dose")
  } else {
    paste0("dose_vec <- ", settings$dose, "  # Same dose for all subjects")
  }
  
  blq_desc <- switch(blq_rule,
    "rule1" = "Rule 1: Pre-first-quantifiable = 0, post-last-quantifiable = missing, between = 0",
    "rule2" = "Rule 2: All BLQ = 0",
    "rule3" = "Rule 3: All BLQ = excluded (NA)",
    "rule4" = "Rule 4: All BLQ = LLOQ/2",
    "rule5" = "Rule 5: Pre-Cmax = 0, post-Cmax = missing",
    "rule6" = "Rule 6: Pre-first-quantifiable = LLOQ/2, rest = 0",
    paste("Unknown rule:", blq_rule)
  )
  
  composite_key_code <- if (!is.null(col_map$treatment)) {
    paste0(
      '\n# Create composite key for crossover data (Subject||Treatment)\n',
      'data$.nca_key <- paste(data[[', deparse(col_map$subject), ']],\n',
      '                       data[[', deparse(col_map$treatment), ']], sep = "||")\n',
      'nca_key <- ".nca_key"\n'
    )
  } else {
    paste0('\nnca_key <- ', deparse(col_map$subject), '\n')
  }
  
  split_code <- if (!is.null(col_map$treatment)) {
    paste0(
      '\n# Split composite key back into Subject and Treatment\n',
      'parts <- strsplit(as.character(result[[1]]), "\\\\|\\\\|")\n',
      'result$Subject   <- sapply(parts, `[`, 1)\n',
      'result$Treatment <- sapply(parts, `[`, 2)\n',
      'result[[1]] <- NULL  # Remove composite key column\n'
    )
  } else ""
  
  script <- paste0(
'# ============================================================================
# NCA Analysis Reproducibility Script
# ============================================================================
# Generated by NCA Assistant v', 
    tryCatch(get("APP_VERSION", envir = globalenv()), error = function(e) "1.0"), '
# Date: ', format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), '
#
# This script independently reproduces the NCA analysis performed in the app.
# It requires only R and the NonCompart package (installed automatically).
#
# INSTRUCTIONS:
#   1. Place this script and the data file in the same folder
#   2. Open R or RStudio
#   3. Set your working directory to that folder:
#        setwd("path/to/your/folder")
#   4. Run this script:
#        source("reproduce_analysis.R")
#   5. The script produces "reproduced_results.csv" for comparison
# ============================================================================


# --- Step 1: Install required packages (if not already installed) -----------

required_packages <- c("NonCompart", "dplyr")
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
  }
}
library(NonCompart)


# --- Step 2: Read the original data file ------------------------------------

data_file <- "', file_name, '"

if (!file.exists(data_file)) {
  stop("Data file not found: ", data_file, 
       "\\nPlace the original data file in the same folder as this script.")
}

file_ext <- tolower(tools::file_ext(data_file))
if (file_ext %in% c("csv", "txt")) {
  data <- read.csv(data_file, stringsAsFactors = FALSE)
} else if (file_ext %in% c("xlsx", "xls")) {
  if (!requireNamespace("readxl", quietly = TRUE))
    install.packages("readxl", repos = "https://cloud.r-project.org")
  data <- readxl::read_excel(data_file)
  data <- as.data.frame(data)
} else if (file_ext == "tsv") {
  data <- read.delim(data_file, stringsAsFactors = FALSE)
}

cat("Data loaded:", nrow(data), "rows,", ncol(data), "columns\\n")


# --- Step 3: Verify data integrity ------------------------------------------

if (requireNamespace("digest", quietly = TRUE)) {
  file_hash <- digest::digest(file = data_file, algo = "sha256")
  cat("SHA-256 hash:", file_hash, "\\n")
} else {
  cat("Install the digest package to verify data integrity: install.packages(\\"digest\\")\\n")
}


# --- Step 4: Column mapping --------------------------------------------------
# These are the columns identified during the analysis.

subject_col <- ', deparse(col_map$subject), '
time_col    <- ', deparse(col_map$time), '
conc_col    <- ', deparse(col_map$conc), '
cat("Subject column:", subject_col, "\\n")
cat("Time column:   ", time_col, "\\n")
cat("Conc column:   ", conc_col, "\\n")


# --- Step 5: Handle BLQ values -----------------------------------------------
# BLQ rule applied: ', blq_desc, '
# LLOQ value: ', lloq, '

# Convert concentration to numeric (BLQ text entries become NA)
data[[conc_col]] <- suppressWarnings(as.numeric(as.character(data[[conc_col]])))
data[[time_col]] <- suppressWarnings(as.numeric(data[[time_col]]))
',
if (lloq > 0) {
  paste0(
    'lloq <- ', lloq, '\n',
    '# Apply BLQ rule: ', blq_desc, '\n',
    switch(blq_rule,
      "rule1" = paste0(
        'for (s in unique(data[[subject_col]])) {\n',
        '  idx <- which(data[[subject_col]] == s)\n',
        '  conc_s <- data[[conc_col]][idx]\n',
        '  is_blq <- !is.na(conc_s) & conc_s < lloq\n',
        '  quant <- which(!is_blq & !is.na(conc_s))\n',
        '  if (length(quant) == 0) { data[[conc_col]][idx[is_blq]] <- NA; next }\n',
        '  first_q <- min(quant); last_q <- max(quant)\n',
        '  if (first_q > 1) data[[conc_col]][idx[1:(first_q-1)]][is_blq[1:(first_q-1)]] <- 0\n',
        '  if (last_q < length(idx)) data[[conc_col]][idx[(last_q+1):length(idx)]][is_blq[(last_q+1):length(idx)]] <- NA\n',
        '  between <- first_q:last_q\n',
        '  data[[conc_col]][idx[between]][is_blq[between]] <- 0\n',
        '}\n'),
      "rule2" = 'data[[conc_col]][!is.na(data[[conc_col]]) & data[[conc_col]] < lloq] <- 0\n',
      "rule3" = 'data[[conc_col]][!is.na(data[[conc_col]]) & data[[conc_col]] < lloq] <- NA\n',
      "rule4" = paste0('data[[conc_col]][!is.na(data[[conc_col]]) & data[[conc_col]] < lloq] <- ', lloq/2, '\n'),
      "rule5" = paste0(
        'for (s in unique(data[[subject_col]])) {\n',
        '  idx <- which(data[[subject_col]] == s)\n',
        '  is_blq <- !is.na(data[[conc_col]][idx]) & data[[conc_col]][idx] < lloq\n',
        '  tmax_i <- which.max(data[[conc_col]][idx])\n',
        '  pre <- idx[1:tmax_i]; post <- if (tmax_i < length(idx)) idx[(tmax_i+1):length(idx)] else integer(0)\n',
        '  data[[conc_col]][intersect(pre, idx[is_blq])] <- 0\n',
        '  data[[conc_col]][intersect(post, idx[is_blq])] <- NA\n',
        '}\n'),
      "rule6" = paste0(
        'for (s in unique(data[[subject_col]])) {\n',
        '  idx <- which(data[[subject_col]] == s)\n',
        '  conc_s <- data[[conc_col]][idx]\n',
        '  is_blq <- !is.na(conc_s) & conc_s < lloq\n',
        '  quant <- which(!is_blq & !is.na(conc_s))\n',
        '  if (length(quant) == 0) { data[[conc_col]][idx[is_blq]] <- ', lloq/2, '; next }\n',
        '  first_q <- min(quant)\n',
        '  if (first_q > 1) data[[conc_col]][idx[1:(first_q-1)]][is_blq[1:(first_q-1)]] <- ', lloq/2, '\n',
        '  from_q <- first_q:length(idx)\n',
        '  data[[conc_col]][idx[from_q]][is_blq[from_q]] <- 0\n',
        '}\n'),
      ""
    )
  )
} else {
  "# No BLQ processing applied (LLOQ = 0)\n"
},
'
# Remove rows with missing time
data <- data[!is.na(data[[time_col]]), ]
data <- data[order(data[[subject_col]], data[[time_col]]), ]


# --- Step 6: Set dose --------------------------------------------------------

', dose_code, '


# --- Step 7: Run Non-Compartmental Analysis -----------------------------------
# Engine: NonCompart::tblNCA (Kim et al., Transl Clin Pharmacol, 2018)
# Administration: ', adm, '
# Trapezoidal method: ', down, '
# Minimum R-squared for half-life: ', settings$r2adj_threshold, '
# Steady state: ', settings$is_steady_state, '
', composite_key_code, '
result <- NonCompart::tblNCA(
  data,
  key    = nca_key,
  colTime = time_col,
  colConc = conc_col,
  dose    = dose_vec,
  adm     = "', adm, '",
  dur     = ', settings$infusion_duration, ',
  doseUnit = "', settings$dose_unit, '",
  timeUnit = "', settings$time_unit, '",
  concUnit = "', settings$conc_unit, '",
  down     = "', down, '",
  R2ADJ    = ', settings$r2adj_threshold, ',
  SS       = ', toupper(as.character(settings$is_steady_state)), '
)
', split_code, '

# --- Step 8: Apply manual lambda_z overrides (if any) -----------------------
', if (!is.null(lz_overrides) && length(lz_overrides) > 0) {
  override_lines <- sapply(names(lz_overrides), function(k) {
    ov <- lz_overrides[[k]]
    profile <- ov$profile
    lz_val <- ov$adjusted_lambda_z
    orig_val <- if (!is.na(ov$original_lambda_z)) ov$original_lambda_z else "NA"
    paste0(
      '# Override: ', profile, ' (original \u03bbz = ', signif(as.numeric(orig_val), 5),
      ' -> adjusted \u03bbz = ', signif(lz_val, 5), ', ', ov$points_used, ' points)\n',
      if (grepl(" \\| ", profile)) {
        parts <- strsplit(profile, " \\| ")[[1]]
        paste0('idx <- which(result$Subject == "', trimws(parts[1]),
               '" & result$Treatment == "', trimws(parts[2]), '")')
      } else {
        paste0('idx <- which(result[[1]] == "', profile, '")')
      },
      '\nif (length(idx) == 1) {\n',
      '  result$LAMZ[idx]   <- ', signif(lz_val, 8), '\n',
      '  result$LAMZHL[idx] <- log(2) / ', signif(lz_val, 8), '\n',
      '  clast <- as.numeric(result$CLST[idx])\n',
      '  auclst <- as.numeric(result$AUCLST[idx])\n',
      '  if (!is.na(clast) && ', signif(lz_val, 8), ' > 0) {\n',
      '    result$AUCIFO[idx] <- auclst + clast / ', signif(lz_val, 8), '\n',
      '  }\n',
      '}\n')
  })
  paste0('\ncat("Applying ", ', length(lz_overrides), ', " manual lambda_z override(s)...\\n")\n',
         paste(override_lines, collapse = "\n"))
} else "", '

# --- Step 9: Save results ----------------------------------------------------

write.csv(result, "reproduced_results.csv", row.names = FALSE)
cat("\\nResults saved to: reproduced_results.csv\\n")
cat("Subjects analyzed:", nrow(result), "\\n")
cat("\\nDone. Compare reproduced_results.csv with the app output.\\n")
')
  
  script
}


#' Generate standalone R script for single-subject NCA
#' @param time_vec Numeric vector of time values
#' @param conc_vec Numeric vector of concentration values
#' @param settings List of NCA settings
#' @param subject_label Label for the subject
#' @param file_name Original file name (or NULL for manual entry)
generate_single_nca_script <- function(time_vec, conc_vec, settings,
                                        subject_label = "Subject",
                                        file_name = NULL) {
  
  adm_map <- c(extravascular = "Extravascular", iv_bolus = "Bolus",
                iv_infusion = "Infusion")
  adm <- adm_map[settings$admin_route]
  down <- if (settings$trap_method == "log") "Log" else "Linear"
  
  time_str <- paste(time_vec, collapse = ", ")
  conc_str <- paste(conc_vec, collapse = ", ")
  
  data_section <- if (!is.null(file_name) && nchar(file_name) > 0) {
    paste0(
'# --- Step 2: Read the data file and extract this subject ---

data_file <- "', file_name, '"
if (!file.exists(data_file)) {
  stop("Data file not found: ", data_file)
}

file_ext <- tolower(tools::file_ext(data_file))
if (file_ext %in% c("csv", "txt")) {
  data <- read.csv(data_file, stringsAsFactors = FALSE)
} else if (file_ext %in% c("xlsx", "xls")) {
  if (!requireNamespace("readxl", quietly = TRUE))
    install.packages("readxl", repos = "https://cloud.r-project.org")
  data <- as.data.frame(readxl::read_excel(data_file))
}

# The analysis was performed on the following data:
time <- c(', time_str, ')
conc <- c(', conc_str, ')
cat("Subject: ', subject_label, '\\n")
cat("Time points:", length(time), "\\n")
')
  } else {
    paste0(
'# --- Step 2: Data (entered manually in the app) ---

time <- c(', time_str, ')
conc <- c(', conc_str, ')
cat("Subject: ', subject_label, '\\n")
cat("Time points:", length(time), "\\n")
')
  }
  
  paste0(
'# ============================================================================
# Single-Subject NCA Reproducibility Script
# ============================================================================
# Generated by NCA Assistant v',
    tryCatch(get("APP_VERSION", envir = globalenv()), error = function(e) "1.0"), '
# Date: ', format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), '
#
# This script reproduces the single-subject NCA performed in the app.
#
# INSTRUCTIONS:
#   1. Open R or RStudio
#   2. Run this script: source("reproduce_analysis.R")
# ============================================================================


# --- Step 1: Install required packages ---

if (!requireNamespace("NonCompart", quietly = TRUE)) {
  install.packages("NonCompart", repos = "https://cloud.r-project.org")
}
library(NonCompart)

', data_section, '

# --- Step 3: Run Non-Compartmental Analysis ---
# Engine: NonCompart::sNCA
# Administration: ', adm, '
# Trapezoidal method: ', down, '
# Steady state: ', settings$is_steady_state, '

result <- NonCompart::sNCA(
  x        = time,
  y        = conc,
  dose     = ', settings$dose, ',
  adm      = "', adm, '",
  dur      = ', settings$infusion_duration, ',
  doseUnit = "', settings$dose_unit, '",
  timeUnit = "', settings$time_unit, '",
  concUnit = "', settings$conc_unit, '",
  down     = "', down, '",
  R2ADJ    = 0.7,
  SS       = ', toupper(as.character(settings$is_steady_state)), '
)


# --- Step 4: Display results ---

result_df <- data.frame(
  Parameter = names(result),
  Value     = as.character(result),
  stringsAsFactors = FALSE
)
write.csv(result_df, "reproduced_results.csv", row.names = FALSE)
cat("\\nResults saved to: reproduced_results.csv\\n")
cat("Parameters computed:", length(result), "\\n")
cat("\\nKey parameters:\\n")
for (p in c("CMAX", "TMAX", "AUCLST", "AUCIFO", "LAMZHL", "CLFO", "VZFO")) {
  if (p %in% names(result)) cat(sprintf("  %s = %s\\n", p, result[p]))
}
cat("\\nDone.\\n")
')
}


#' Generate the analysis summary HTML document
#' @return Character string containing HTML
generate_summary_html <- function(settings, col_map, file_name, file_hash,
                                   blq_rule, lloq, analyst, study_name,
                                   n_subjects, n_obs, analysis_type = "NCA",
                                   lz_overrides = NULL) {
  
  ver <- tryCatch(get("APP_VERSION", envir = globalenv()), error = function(e) "?")
  r_ver <- tryCatch(R.version.string, error = function(e) "R")
  
  pkg_ver <- function(pkg) {
    tryCatch(as.character(packageVersion(pkg)), error = function(e) "?")
  }
  
  blq_desc <- switch(blq_rule,
    "rule1" = "Rule 1 (Standard): Pre-first-quantifiable = 0, post-last-quantifiable = missing",
    "rule2" = "Rule 2: All BLQ = 0",
    "rule3" = "Rule 3: All BLQ excluded",
    "rule4" = "Rule 4: All BLQ = LLOQ/2",
    "rule5" = "Rule 5: Pre-Cmax = 0, post-Cmax = missing",
    "rule6" = "Rule 6: First BLQ = LLOQ/2, rest = 0",
    blq_rule
  )
  
  route_desc <- switch(settings$admin_route,
    "extravascular" = "Extravascular (oral / IM / SC)",
    "iv_bolus" = "Intravenous bolus",
    "iv_infusion" = "Intravenous infusion",
    settings$admin_route
  )
  
  trap_desc <- if (settings$trap_method == "log") "Linear-up / Log-down" else "Linear"
  
  paste0('<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Analysis Record — ', htmltools::htmlEscape(study_name), '</title>
<style>
  body { font-family: "Segoe UI", Calibri, Arial, sans-serif; max-width: 800px;
         margin: 2rem auto; padding: 0 1rem; color: #2C3E50; font-size: 14px; line-height: 1.6; }
  h1 { color: #2C3E50; border-bottom: 3px solid #3498DB; padding-bottom: 0.5rem; }
  h2 { color: #3498DB; margin-top: 2rem; }
  h3 { color: #2C3E50; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
  th { background: #f5f5f5; }
  .info-box { background: #EBF5FB; border-left: 4px solid #3498DB;
              padding: 12px 16px; margin: 1rem 0; border-radius: 4px; }
  .hash { font-family: monospace; background: #f5f5f5; padding: 2px 6px; border-radius: 3px; word-break: break-all; }
  .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd;
            font-size: 12px; color: #7f8c8d; }
</style>
</head>
<body>

<h1>Complete Analysis Record</h1>

<div class="info-box">
<strong>What is this document?</strong><br>
This package contains everything needed to independently reproduce the pharmacokinetic
analysis. The R script (<code>reproduce_analysis.R</code>) repeats the exact same analysis
step by step, without requiring the NCA Assistant app. The SHA-256 hash verifies that
the data file has not been modified since the analysis was performed.
</div>

<h2>1. Study Information</h2>
<table>
<tr><th>Study name</th><td>', htmltools::htmlEscape(study_name), '</td></tr>
<tr><th>Analyst</th><td>', htmltools::htmlEscape(analyst), '</td></tr>
<tr><th>Analysis type</th><td>', analysis_type, '</td></tr>
<tr><th>Date &amp; time</th><td>', format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), '</td></tr>
<tr><th>Subjects</th><td>', n_subjects, '</td></tr>
<tr><th>Observations</th><td>', n_obs, '</td></tr>
</table>

<h2>2. Data File</h2>
<table>
<tr><th>File name</th><td><code>', htmltools::htmlEscape(file_name), '</code></td></tr>
<tr><th>SHA-256 hash</th><td><span class="hash">', file_hash, '</span></td></tr>
</table>
<p style="font-size:12px; color:#7f8c8d;">
The SHA-256 hash is a digital fingerprint of the data file. If you recalculate the hash
of your data file and it matches the value above, the file has not been modified since
this analysis was performed.
</p>

<h2>3. Analysis Settings</h2>
<table>
<tr><th>Route of administration</th><td>', route_desc, '</td></tr>',
if (settings$admin_route == "iv_infusion")
  paste0('<tr><th>Infusion duration</th><td>', settings$infusion_duration, ' ', settings$time_unit, '</td></tr>') else "",
'<tr><th>Dose</th><td>', if (length(settings$dose) > 1) paste(unique(settings$dose), collapse=", ") else settings$dose,
  ' ', settings$dose_unit, if (length(settings$dose) > 1) " (per subject from data)" else "", '</td></tr>
<tr><th>Steady state</th><td>', if (settings$is_steady_state) "Yes" else "No", '</td></tr>
<tr><th>Trapezoidal method</th><td>', trap_desc, '</td></tr>
<tr><th>Min R&sup2; for half-life</th><td>', settings$r2adj_threshold, '</td></tr>
<tr><th>BLQ handling</th><td>', blq_desc, '</td></tr>
<tr><th>LLOQ</th><td>', lloq, ' ', settings$conc_unit, '</td></tr>
<tr><th>Units</th><td>Dose: ', settings$dose_unit, ' | Time: ', settings$time_unit,
  ' | Conc: ', settings$conc_unit, '</td></tr>
</table>

<h2>4. Column Mapping</h2>
<table>
<tr><th>Subject</th><td>', col_map$subject, '</td></tr>
<tr><th>Time</th><td>', col_map$time, '</td></tr>
<tr><th>Concentration</th><td>', col_map$conc, '</td></tr>',
if (!is.null(col_map$treatment)) paste0('<tr><th>Treatment</th><td>', col_map$treatment, '</td></tr>') else "",
if (!is.null(col_map$period)) paste0('<tr><th>Period</th><td>', col_map$period, '</td></tr>') else "",
if (!is.null(col_map$sequence)) paste0('<tr><th>Sequence</th><td>', col_map$sequence, '</td></tr>') else "",
if (!is.null(col_map$dose)) paste0('<tr><th>Dose</th><td>', col_map$dose, '</td></tr>') else "",
'</table>

<h2>5. Statistical Methods</h2>
<h3>Non-Compartmental Analysis</h3>
<p>Pharmacokinetic parameters were estimated by non-compartmental analysis
using the NonCompart R package (version ', pkg_ver("NonCompart"),
'; Kim et al., 2018). The area under the concentration&ndash;time curve
(AUC<sub>0&ndash;t</sub>) was calculated using the ', tolower(trap_desc),
' trapezoidal method. The terminal elimination rate constant (&lambda;<sub>z</sub>)
was estimated by log-linear regression of the terminal phase, selecting the
combination of points with the highest adjusted R&sup2; (&ge; ',
settings$r2adj_threshold, '). The terminal half-life was calculated as
ln(2)/&lambda;<sub>z</sub>. C<sub>max</sub> and T<sub>max</sub> were obtained
directly from the observed data.</p>',
if (settings$is_steady_state)
'<p>Steady-state analysis: AUC<sub>0&ndash;t</sub> represents AUC within the dosing
interval (AUC<sub>&tau;</sub>). Clearance was calculated as Dose/AUC<sub>&tau;</sub>.</p>' else "",
if (lloq > 0) paste0('<p>Concentrations below the LLOQ (', lloq, ' ', settings$conc_unit,
  ') were handled using ', blq_desc, '.</p>') else "",
'

<h2>6. Software Environment</h2>
<table>
<tr><th>NCA Assistant</th><td>v', ver, '</td></tr>
<tr><th>R</th><td>', r_ver, '</td></tr>
<tr><th>NonCompart</th><td>', pkg_ver("NonCompart"), '</td></tr>
<tr><th>nlme</th><td>', pkg_ver("nlme"), '</td></tr>
<tr><th>PowerTOST</th><td>', pkg_ver("PowerTOST"), '</td></tr>
<tr><th>Operating system</th><td>', sessionInfo()$running, '</td></tr>
</table>

<h2>7. How to Reproduce</h2>
<div class="info-box">
<strong>Instructions:</strong>
<ol>
<li>Place <code>reproduce_analysis.R</code> and <code>', htmltools::htmlEscape(file_name),
'</code> in the same folder.</li>
<li>Open R or RStudio.</li>
<li>Set the working directory to that folder:<br>
<code>setwd("path/to/your/folder")</code></li>
<li>Run the script:<br>
<code>source("reproduce_analysis.R")</code></li>
<li>The script installs any missing packages automatically and produces
<code>reproduced_results.csv</code>.</li>
<li>Compare with <code>results.xlsx</code> from this package.</li>
</ol>
</div>

<h2>8. References</h2>
<p>Kim H, Yun H, Cho S, et al. NonCompart: Noncompartmental Analysis for
Pharmacokinetic Data. <em>Transl Clin Pharmacol</em>. 2018;26(1):10&ndash;15.</p>
<p>R Core Team. R: A Language and Environment for Statistical Computing.
R Foundation for Statistical Computing, Vienna, Austria.</p>

', if (!is.null(lz_overrides) && length(lz_overrides) > 0) {
  rows <- sapply(lz_overrides, function(ov) {
    paste0('<tr><td>', ov$profile, '</td>',
           '<td>', if (!is.na(ov$original_lambda_z)) signif(ov$original_lambda_z, 5) else "N/A", '</td>',
           '<td>', signif(ov$adjusted_lambda_z, 5), '</td>',
           '<td>', if (!is.na(ov$original_r2adj)) signif(ov$original_r2adj, 4) else "N/A", '</td>',
           '<td>', if (!is.na(ov$adjusted_r2adj)) signif(ov$adjusted_r2adj, 4) else "N/A", '</td>',
           '<td>', ov$points_used, '</td></tr>')
  })
  paste0('<h2>9. Manual Lambda-z Overrides</h2>\n',
         '<p>', length(lz_overrides), ' profile(s) had manual terminal phase adjustments:</p>\n',
         '<table border="1" cellpadding="4" style="border-collapse: collapse; font-size: 13px;">\n',
         '<tr style="background:#eee;"><th>Profile</th><th>Original &lambda;z</th>',
         '<th>Adjusted &lambda;z</th><th>Original R&sup2;</th>',
         '<th>Adjusted R&sup2;</th><th>Points</th></tr>\n',
         paste(rows, collapse = '\n'), '\n</table>\n',
         '<p style="font-size:12px;color:#666;">These adjustments are reflected in the results Excel ',
         'and are applied by the reproducibility script (reproduce_analysis.R).</p>\n')
} else '', '

<div class="footer">
Generated by NCA Assistant v', ver, ' on ', format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
'<br>This document is part of the Complete Analysis Record and should be kept
together with the other files in this package.
</div>

</body>
</html>')
}


#' Create the complete analysis record zip file
#' @param output_path Path to write the zip file
#' @param results Data frame of NCA results
#' @param settings List of analysis settings
#' @param col_map Column mapping
#' @param original_file_path Path to the original uploaded data file
#' @param original_file_name Name of the original file
#' @param blq_rule BLQ rule used
#' @param lloq LLOQ value
#' @param analyst Analyst name
#' @param study_name Study name
#' @param summary_stats Optional summary statistics data frame
#' @param be_results Optional BE results list
create_analysis_record <- function(output_path, results, settings, col_map,
                                    original_file_path, original_file_name,
                                    blq_rule, lloq, analyst = "Analyst",
                                    study_name = "Untitled Study",
                                    summary_stats = NULL,
                                    be_results = NULL,
                                    lz_overrides = NULL,
                                    viz_settings = NULL) {
  
  # Create temp directory
  tmp <- tempdir()
  rec_dir <- file.path(tmp, "analysis_record")
  if (dir.exists(rec_dir)) unlink(rec_dir, recursive = TRUE)
  dir.create(rec_dir, recursive = TRUE)
  
  n_subjects <- if ("Subject" %in% names(results)) length(unique(results$Subject))
                else nrow(results)
  n_obs <- if (!is.null(settings$n_obs)) settings$n_obs else "?"
  analysis_type <- if (!is.null(be_results)) "Bioequivalence" else "Non-Compartmental Analysis"
  
  # 1. Results Excel
  tryCatch({
    wb <- openxlsx::createWorkbook()
    openxlsx::addWorksheet(wb, "Individual_Parameters")
    openxlsx::writeData(wb, 1, rename_nca_columns(results))
    if (!is.null(summary_stats)) {
      openxlsx::addWorksheet(wb, "Summary_Statistics")
      openxlsx::writeData(wb, 2, rename_summary_columns(summary_stats))
    }
    if (!is.null(be_results)) {
      openxlsx::addWorksheet(wb, "BE_Confidence_Intervals")
      openxlsx::writeData(wb, "BE_Confidence_Intervals", rename_be_columns(be_results$ci_table))
      for (p in names(be_results$anova)) {
        sn <- substr(paste0("ANOVA_", friendly_name(p)), 1, 31)
        openxlsx::addWorksheet(wb, sn)
        df <- as.data.frame(be_results$anova[[p]])
        df$Source <- rownames(df)
        openxlsx::writeData(wb, sn, df)
      }
    }
    openxlsx::saveWorkbook(wb, file.path(rec_dir, "results.xlsx"), overwrite = TRUE)
  }, error = function(e) warning("Could not create results.xlsx: ", e$message))
  
  # 2. Settings JSON
  tryCatch({
    settings_export <- list(
      schema_version  = "1.2",   # increment when settings structure changes
      app_version     = tryCatch(get("APP_VERSION", envir = globalenv()), error = function(e) "?"),
      r_version       = R.version.string,
      timestamp       = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
      analyst         = analyst,
      study_name      = study_name,
      analysis_type   = analysis_type,
      input_file      = original_file_name,
      column_mapping  = col_map,
      admin_route     = settings$admin_route,
      dose            = settings$dose,
      dose_source     = if (length(settings$dose) > 1) "per_subject" else "single",
      dose_unit       = settings$dose_unit,
      time_unit       = settings$time_unit,
      conc_unit       = settings$conc_unit,
      infusion_dur    = settings$infusion_duration,
      steady_state    = settings$is_steady_state,
      trap_method     = settings$trap_method,
      r2adj_threshold = settings$r2adj_threshold,
      blq_rule        = blq_rule,
      lloq            = lloq,
      packages = list(
        NonCompart = tryCatch(as.character(packageVersion("NonCompart")), error = function(e) "?"),
        nlme       = tryCatch(as.character(packageVersion("nlme")), error = function(e) "?"),
        PowerTOST  = tryCatch(as.character(packageVersion("PowerTOST")), error = function(e) "?")
      )
    )
    if (!is.null(lz_overrides) && length(lz_overrides) > 0) {
      settings_export$lz_overrides <- lz_overrides
    }
    if (!is.null(viz_settings) && length(viz_settings) > 0) {
      settings_export$visualization <- viz_settings
    }
    writeLines(jsonlite::toJSON(settings_export, pretty = TRUE, auto_unbox = TRUE),
               file.path(rec_dir, "analysis_settings.json"))
  }, error = function(e) warning("Could not create settings JSON: ", e$message))
  
  # 3. Reproducibility R script
  tryCatch({
    script <- generate_nca_script(settings, col_map, original_file_name,
                                   blq_rule, lloq, lz_overrides)
    writeLines(script, file.path(rec_dir, "reproduce_analysis.R"))
  }, error = function(e) warning("Could not create R script: ", e$message))
  
  # 4. Data integrity
  tryCatch({
    file_hash <- if (requireNamespace("digest", quietly = TRUE)) {
      digest::digest(file = original_file_path, algo = "sha256")
    } else {
      "digest package not available — hash not computed"
    }
    integrity <- paste0(
      "Data Integrity Verification\n",
      "===========================\n\n",
      "File name:    ", original_file_name, "\n",
      "File size:    ", file.info(original_file_path)$size, " bytes\n",
      "SHA-256 hash: ", file_hash, "\n",
      "Computed at:  ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n\n",
      "To verify: in R, run:\n",
      "  digest::digest(file = \"", original_file_name, "\", algo = \"sha256\")\n",
      "The result should match the hash above.\n"
    )
    writeLines(integrity, file.path(rec_dir, "data_integrity.txt"))
  }, error = function(e) warning("Could not create integrity file: ", e$message))
  
  # 5. Summary HTML
  tryCatch({
    file_hash <- if (requireNamespace("digest", quietly = TRUE)) {
      digest::digest(file = original_file_path, algo = "sha256")
    } else "not computed"
    html <- generate_summary_html(settings, col_map, original_file_name,
                                   file_hash, blq_rule, lloq, analyst,
                                   study_name, n_subjects, n_obs, analysis_type,
                                   lz_overrides)
    writeLines(html, file.path(rec_dir, "analysis_summary.html"))
  }, error = function(e) warning("Could not create summary HTML: ", e$message))
  
  # 6. Copy original data file
  tryCatch({
    file.copy(original_file_path, file.path(rec_dir, original_file_name),
              overwrite = TRUE)
  }, error = function(e) warning("Could not copy data file: ", e$message))
  
  # Create zip — without changing the global working directory.
  # We use system2("zip", "-j") with absolute paths, which strips directory
  # prefixes (-j = junk paths) without requiring setwd(). utils::zip() needs
  # a working directory change to strip paths, which is not session-safe in
  # a multi-session Shiny deployment.
  files_to_zip <- list.files(rec_dir, full.names = TRUE)
  abs_output   <- normalizePath(output_path, mustWork = FALSE)
  
  zip_result <- tryCatch({
    # Primary: system zip with absolute paths, no setwd needed
    res <- system2("zip",
                   args   = c("-j", shQuote(abs_output),
                               shQuote(files_to_zip)),
                   stdout = FALSE, stderr = FALSE)
    if (!is.null(res) && res != 0) stop("system zip returned non-zero exit")
    res
  }, error = function(e) {
    # Fallback when system zip is unavailable.
    # Use withr::with_dir() if available — avoids modifying global working
    # directory. Falls back to a scoped setwd with guaranteed on.exit restore.
    tryCatch({
      if (requireNamespace("withr", quietly = TRUE)) {
        withr::with_dir(rec_dir, {
          utils::zip(abs_output, files = basename(files_to_zip), flags = "-j")
        })
      } else {
        old_wd <- setwd(rec_dir)
        on.exit(setwd(old_wd), add = TRUE)
        utils::zip(abs_output, files = basename(files_to_zip), flags = "-j")
      }
    }, error = function(e2) {
      warning("Could not create zip archive: ", e2$message)
    })
  })
  
  unlink(rec_dir, recursive = TRUE)
  
  invisible(output_path)
}
